#Preparando ambiente

In [5]:
!pip install transformers==5.0.0rc0
!pip install mistral-common

Collecting transformers==5.0.0rc0
  Downloading transformers-5.0.0rc0-py3-none-any.whl.metadata (35 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==5.0.0rc0) (3.20.0)
Collecting huggingface-hub<2.0,>=1.0.0 (from transformers==5.0.0rc0)
  Downloading huggingface_hub-1.3.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==5.0.0rc0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==5.0.0rc0) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==5.0.0rc0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==5.0.0rc0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==5.0.0rc0) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==5.0.0rc0) (0.22.1)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers==5.0.0rc0) (0.20.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==5.0.0rc0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==5.0.0rc0) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.0.0->transformers==5.0.0rc0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.0.0->transformers==5.0.0rc0) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.0.0->transformers==5.0.0rc0) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.0.0->transformers==5.0.0rc0) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.0.0->transformers==5.0.0rc0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==5.0.0rc0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==5.0.0rc0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==5.0.0rc0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==5.0.0rc0) (2025.11.12)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers==5.0.0rc0) (8.3.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.0.0->transformers==5.0.0rc0) (4.12.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.0.0->transformers==5.0.0rc0) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.0.0->transformers==5.0.0rc0) (0.16.0)
Downloading transformers-5.0.0rc0-py3-none-any.whl (9.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 25.5 MB/s eta 0:00:00
Downloading huggingface_hub-1.3.1-py3-none-any.whl (533 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 533.4/533.4 kB 52.8 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.36.0
    Uninstalling huggingface-hub-0.36.0:
      Successfully uninstalled huggingface-hub-0.36.0
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.3
    Uninstalling transformers-4.57.3:
      Successfully uninstalled transformers-4.57.3
Successfully installed huggingface-hub-1.3.1 transformers-5.0.0rc0

Collecting mistral-common
  Downloading mistral_common-1.8.8-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: pydantic<3.0,>=2.7 in /usr/local/lib/python3.12/dist-packages (from mistral-common) (2.12.3)
Requirement already satisfied: jsonschema>=4.21.1 in /usr/local/lib/python3.12/dist-packages (from mistral-common) (4.25.1)
Requirement already satisfied: typing-extensions>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from mistral-common) (4.15.0)
Requirement already satisfied: tiktoken>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from mistral-common) (0.12.0)
Requirement already satisfied: pillow>=10.3.0 in /usr/local/lib/python3.12/dist-packages (from mistral-common) (11.3.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mistral-common) (2.32.4)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from mistral-common) (2.0.2)
Collecting pydantic-extra-types>=2.10.5 (from pydantic-extra-types[pycountry]>=2.10.5->mistral-common)
  Downloading pydantic_extra_types-2.11.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral-common) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral-common) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral-common) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral-common) (0.30.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=2.7->mistral-common) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=2.7->mistral-common) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=2.7->mistral-common) (0.4.2)
Collecting pycountry>=23 (from pydantic-extra-types[pycountry]>=2.10.5->mistral-common)
  Downloading pycountry-24.6.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->mistral-common) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->mistral-common) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->mistral-common) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->mistral-common) (2025.11.12)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken>=0.7.0->mistral-common) (2025.11.3)
Downloading mistral_common-1.8.8-py3-none-any.whl (6.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 152.9 MB/s eta 0:00:00
Downloading pydantic_extra_types-2.11.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.3/74.3 kB 10.1 MB/s eta 0:00:00
Downloading pycountry-24.6.1-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 149.9 MB/s eta 0:00:00
Installing collected packages: pycountry, pydantic-extra-types, mistral-common
Successfully installed mistral-common-1.8.8 pycountry-24.6.1 pydantic-extra-types-2.11.0

In [1]:
from transformers import Mistral3ForConditionalGeneration, MistralCommonBackend, FineGrainedFP8Config
from datetime import datetime
from zoneinfo import ZoneInfo
import pandas as pd
import random
import torch
import re

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Carregando dataset ASSIN2

In [3]:
def gera_df():

  splits = {'train': 'data/train-00000-of-00001.parquet', 'test': 'data/test-00000-of-00001.parquet', 'validation': 'data/validation-00000-of-00001.parquet'}
  df_assin_2_treino = pd.read_parquet("hf://datasets/nilc-nlp/assin2/" + splits["train"])
  df_assin_2_teste = pd.read_parquet("hf://datasets/nilc-nlp/assin2/" + splits["test"])
  df_assin_2_val = pd.read_parquet("hf://datasets/nilc-nlp/assin2/" + splits["validation"])

  df_assin_2 = pd.concat([df_assin_2_treino, df_assin_2_teste, df_assin_2_val])

  df_assin_2['premise_hypothesis'] = df_assin_2['premise'] + ' ' + df_assin_2['hypothesis']

  occurrence_counts = df_assin_2['premise_hypothesis'].value_counts().reset_index()
  occurrence_counts.columns = ['premise_hypothesis', 'occurrence_count']

  df_assin_2 = df_assin_2.merge(occurrence_counts, on='premise_hypothesis', how='left')

  df_assin_2 = df_assin_2.loc[df_assin_2['occurrence_count'] == 1]

  df_assin_2 = df_assin_2[['sentence_pair_id', 'premise', 'hypothesis', 'relatedness_score',
        'entailment_judgment']]

  df_assin_2.reset_index(drop=True, inplace=True)

  return df_assin_2

In [4]:
def extract_response_character(response_text):
  """
  Extrai o caractere '0' ou '1' da resposta do modelo.
  Args:
    response_text (str): A string de resposta do modelo.
  Returns:
    str: '0' ou '1' se encontrado, caso contrário, None.
  """
  # Use regex to find '0' or '1' potentially preceded by whitespace at the beginning of the string
  match = re.search(r'^[\s]*([01])', response_text)
  if match:
    return match.group(1)
  return None

In [5]:
def zero_shot_prompt(premise, hypothesis):
  return f"""
   Você é um sistema de Reconhecimento de Inferência Textual (RTE) em Português Brasileiro.

    Tarefa:
    Dada uma PREMISSA e uma HIPÓTESE, responda *apenas* com um único caractere:
    - 0 se a hipótese não é inferida da premissa.
    - 1 se a hipótese é logicamente inferida da premissa.

    Regras obrigatórias:
    - NÃO explique.
    - NÃO acrescente texto.
    - NÃO repita o enunciado.
    - NÃO responda nada além de 0 ou 1.

    Premissa: {premise}
    Hipótese: {hypothesis}

    Resposta:
    """

#Ministral 3 - 3B - Reasoning

In [6]:
model_id = "mistralai/Ministral-3-3B-Reasoning-2512"
model = Mistral3ForConditionalGeneration.from_pretrained(
    model_id,
    device_map="auto",
)
tokenizer = MistralCommonBackend.from_pretrained(model_id)

config.json: 0.00B [00:00, ?B/s]

Unrecognized keys in `rope_parameters` for 'rope_type'='yarn': {'max_position_embeddings'}

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/458 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/131 [00:00<?, ?B/s]

tekken.json:   0%|          | 0.00/16.8M [00:00<?, ?B/s]

In [7]:
df_assin_2 = gera_df()

num_records = len(df_assin_2)
random_index = random.randint(0, num_records - 1)
random_index = 2

premissa = df_assin_2.iloc[random_index]['premise']
hipotese = df_assin_2.iloc[random_index]['hypothesis']
prompt = zero_shot_prompt(premissa, hipotese)


inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
output = model.generate(**inputs, max_new_tokens=10)
prompt_len = inputs["input_ids"].shape[1]
generated_tokens = output[0][prompt_len:]
resp = tokenizer.decode(generated_tokens, skip_special_tokens=True)

print(f'Prompt: {prompt}')
print(f'Resposta: {resp}')

Prompt:
   Você é um sistema de Reconhecimento de Inferência Textual (RTE) em Português Brasileiro.

    Tarefa:
    Dada uma PREMISSA e uma HIPÓTESE, responda *apenas* com um único caractere:
    - 0 se a hipótese não é inferida da premissa.
    - 1 se a hipótese é logicamente inferida da premissa.

    Regras obrigatórias:
    - NÃO explique.
    - NÃO acrescente texto.
    - NÃO repita o enunciado.
    - NÃO responda nada além de 0 ou 1.

    Premissa: Uma pessoa tem cabelo loiro e esvoaçante e está tocando violão
    Hipótese: Um guitarrista tem cabelo loiro e esvoaçante

    Resposta:

Resposta:  1

##Teste de Consistência

In [8]:
df_assin_2_first_500 = df_assin_2.head(500)

for j in range(5):
  for i in range(len(df_assin_2_first_500)):
    premissa = df_assin_2_first_500.iloc[i]['premise']
    hipotese = df_assin_2_first_500.iloc[i]['hypothesis']

    prompt = zero_shot_prompt(premissa, hipotese)

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    output = model.generate(**inputs, max_new_tokens=10)
    prompt_len = inputs["input_ids"].shape[1]
    generated_tokens = output[0][prompt_len:]
    resp = tokenizer.decode(generated_tokens, skip_special_tokens=True)

    column_name = f'mistral3b_reasoning_{j}'

    df_assin_2_first_500.loc[i, column_name] = resp

    if i%100==0:
      print(f"{i} - {datetime.now(ZoneInfo("America/Sao_Paulo")).strftime("%Y-%m-%d %H:%M:%S")}")

df_assin_2_first_500.to_csv('/content/drive/MyDrive/Mestrado/TCC Pós/Dados/dados_mistral3b_reasoning_consistencia.csv')

/tmp/ipython-input-4030351167.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_assin_2_first_500.loc[i, column_name] = resp

0 - 2026-01-11 02:22:22
100 - 2026-01-11 02:22:51
200 - 2026-01-11 02:23:22
300 - 2026-01-11 02:23:52
400 - 2026-01-11 02:24:23

/tmp/ipython-input-4030351167.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_assin_2_first_500.loc[i, column_name] = resp

0 - 2026-01-11 02:24:54
100 - 2026-01-11 02:25:25
200 - 2026-01-11 02:25:56
300 - 2026-01-11 02:26:27
400 - 2026-01-11 02:26:58

/tmp/ipython-input-4030351167.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_assin_2_first_500.loc[i, column_name] = resp

0 - 2026-01-11 02:27:29
100 - 2026-01-11 02:28:00
200 - 2026-01-11 02:28:31
300 - 2026-01-11 02:29:02
400 - 2026-01-11 02:29:33

/tmp/ipython-input-4030351167.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_assin_2_first_500.loc[i, column_name] = resp

0 - 2026-01-11 02:30:04
100 - 2026-01-11 02:30:35
200 - 2026-01-11 02:31:06
300 - 2026-01-11 02:31:37
400 - 2026-01-11 02:32:08

/tmp/ipython-input-4030351167.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_assin_2_first_500.loc[i, column_name] = resp

0 - 2026-01-11 02:32:39
100 - 2026-01-11 02:33:10
200 - 2026-01-11 02:33:41
300 - 2026-01-11 02:34:12
400 - 2026-01-11 02:34:43

#Loop de aplicação do prompt em todo o dataset

In [8]:
for i in range(50):
  premissa = df_assin_2.iloc[i]['premise']
  hipotese = df_assin_2.iloc[i]['hypothesis']

  prompt = zero_shot_prompt(premissa, hipotese)

  inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
  output = model.generate(**inputs, max_new_tokens=10)
  prompt_len = inputs["input_ids"].shape[1]
  generated_tokens = output[0][prompt_len:]
  resp = tokenizer.decode(generated_tokens, skip_special_tokens=True)

  df_assin_2.loc[i, 'ministral_3b_reasoning'] = resp

  if i%100==0:
    print(f"{i} - {datetime.now(ZoneInfo("America/Sao_Paulo")).strftime("%Y-%m-%d %H:%M:%S")}")

0 - 2026-01-11 15:23:23

In [10]:
df_assin_2.head(20)

,sentence_pair_id,premise,hypothesis,relatedness_score,entailment_judgment,ministral_3b_reasoning
0,1,Uma criança risonha está segurando uma pistola...,Uma criança está segurando uma pistola de água,4.5,1,1
1,2,Os homens estão cuidadosamente colocando as ma...,Os homens estão colocando bagagens dentro do p...,4.5,1,1
2,3,Uma pessoa tem cabelo loiro e esvoaçante e est...,Um guitarrista tem cabelo loiro e esvoaçante,4.7,1,1
3,4,Batatas estão sendo fatiadas por um homem,O homem está fatiando a batata,4.7,1,1
4,5,Um caminhão está descendo rapidamente um morro,Um caminhão está rapidamente descendo o morro,4.9,1,1
5,6,Um surfista está pegando uma grande onda atrav...,Uma onda grande está sendo surfada por um surf...,4.8,1,1
6,7,Três cachorros pequeninos estão cheirando algo,Três cachorros estão cheirando alguma coisa,4.6,1,1
7,8,Alguns adultos estão sentados nas cadeiras e e...,Dois adultos estão sentados em cadeiras e estã...,4.7,1,0
8,9,A gruta com interior rosa está sendo escalada ...,"Quatro crianças do Oriente Médio, três meninas...",4.9,1,1
9,10,O homem com um chapéu duro está dançando,Um homem com um chapéu duro está dançando,4.9,1,1
10,11,Um menino e uma menina estão brincando do lado...,O menino e a menina estão brincando na academi...,5.0,1,0
11,12,Um jovem casal está dormindo na cama,Um jovem casal está deitado na cama,4.3,1,1
12,13,O monte de homens está jogando rúgbi em um cam...,O grupo de homens está jogando rúgbi em um mon...,4.8,1,1
13,14,A batata está sendo descascada por uma mulher,Uma mulher está descascando a batata,4.9,1,1
14,15,Um homem está de pé em um morro de terra próxi...,Um homem está parado em um morro de terra ao l...,4.3,1,0
15,16,Um homem em uma camisa tingida de roxo está se...,Um homem em uma camisa tingida de roxo está ol...,3.4,1,0
16,17,A menina está passando maquiagem em sua face,Uma menina está aplicando maquiagem em seu rosto,4.9,1,1
17,18,Um homem está picando um tronco com um machado,Um homem está cortando um tronco com um machado,4.9,1,1
18,19,O homem está rachando ovos em uma tigela,A pessoa está quebrando ovos em uma tigela,4.5,1,1
19,20,Uma criança jovem está usando botas feitas de ...,Uma criança jovem está usando botas verdes e b...,4.6,1,1

In [ ]:
for i in range(len(df_assin_2)):
  premissa = df_assin_2.iloc[i]['premise']
  hipotese = df_assin_2.iloc[i]['hypothesis']

  prompt = zero_shot_prompt(premissa, hipotese)

  inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
  output = model.generate(**inputs, max_new_tokens=10)
  prompt_len = inputs["input_ids"].shape[1]
  generated_tokens = output[0][prompt_len:]
  resp = tokenizer.decode(generated_tokens, skip_special_tokens=True)

  df_assin_2.loc[i, 'ministral_3b_reasoning'] = resp

  if i%100==0:
    print(f"{i} - {datetime.now(ZoneInfo("America/Sao_Paulo")).strftime("%Y-%m-%d %H:%M:%S")}")

df_assin_2.to_csv('/content/drive/MyDrive/Mestrado/TCC Pós/Dados/dados_mistral_3b_reasoning.csv')

0 - 2025-12-23 00:13:12
100 - 2025-12-23 00:13:28
200 - 2025-12-23 00:13:44
300 - 2025-12-23 00:14:00
400 - 2025-12-23 00:14:16
500 - 2025-12-23 00:14:32
600 - 2025-12-23 00:14:47
700 - 2025-12-23 00:15:03
800 - 2025-12-23 00:15:19
900 - 2025-12-23 00:15:34
1000 - 2025-12-23 00:15:50
1100 - 2025-12-23 00:16:06
1200 - 2025-12-23 00:16:21
1300 - 2025-12-23 00:16:37
1400 - 2025-12-23 00:16:53
1500 - 2025-12-23 00:17:09
1600 - 2025-12-23 00:17:25
1700 - 2025-12-23 00:17:40
1800 - 2025-12-23 00:17:56
1900 - 2025-12-23 00:18:12
2000 - 2025-12-23 00:18:28
2100 - 2025-12-23 00:18:44
2200 - 2025-12-23 00:19:00
2300 - 2025-12-23 00:19:15
2400 - 2025-12-23 00:19:31
2500 - 2025-12-23 00:19:47
2600 - 2025-12-23 00:20:03
2700 - 2025-12-23 00:20:19
2800 - 2025-12-23 00:20:35
2900 - 2025-12-23 00:20:51
3000 - 2025-12-23 00:21:07
3100 - 2025-12-23 00:21:23
3200 - 2025-12-23 00:21:38
3300 - 2025-12-23 00:21:54
3400 - 2025-12-23 00:22:10
3500 - 2025-12-23 00:22:25
3600 - 2025-12-23 00:22:41
3700 - 2025-12-23 00:22:57
3800 - 2025-12-23 00:23:12
3900 - 2025-12-23 00:23:28
4000 - 2025-12-23 00:23:44
4100 - 2025-12-23 00:23:59
4200 - 2025-12-23 00:24:15
4300 - 2025-12-23 00:24:31
4400 - 2025-12-23 00:24:46
4500 - 2025-12-23 00:25:02
4600 - 2025-12-23 00:25:17
4700 - 2025-12-23 00:25:33
4800 - 2025-12-23 00:25:49
4900 - 2025-12-23 00:26:04
5000 - 2025-12-23 00:26:20
5100 - 2025-12-23 00:26:36
5200 - 2025-12-23 00:26:51
5300 - 2025-12-23 00:27:07
5400 - 2025-12-23 00:27:22
5500 - 2025-12-23 00:27:38
5600 - 2025-12-23 00:27:53
5700 - 2025-12-23 00:28:09
5800 - 2025-12-23 00:28:25
5900 - 2025-12-23 00:28:40
6000 - 2025-12-23 00:28:56
6100 - 2025-12-23 00:29:11
6200 - 2025-12-23 00:29:27
6300 - 2025-12-23 00:29:42
6400 - 2025-12-23 00:29:58
6500 - 2025-12-23 00:30:14
6600 - 2025-12-23 00:30:30
6700 - 2025-12-23 00:30:46
6800 - 2025-12-23 00:31:02
6900 - 2025-12-23 00:31:18
7000 - 2025-12-23 00:31:34
7100 - 2025-12-23 00:31:50
7200 - 2025-12-23 00:32:06
7300 - 2025-12-23 00:32:22
7400 - 2025-12-23 00:32:38
7500 - 2025-12-23 00:32:54
7600 - 2025-12-23 00:33:10
7700 - 2025-12-23 00:33:26
7800 - 2025-12-23 00:33:42
7900 - 2025-12-23 00:33:58
8000 - 2025-12-23 00:34:14
8100 - 2025-12-23 00:34:30
8200 - 2025-12-23 00:34:46
8300 - 2025-12-23 00:35:02
8400 - 2025-12-23 00:35:18
8500 - 2025-12-23 00:35:34
8600 - 2025-12-23 00:35:50
8700 - 2025-12-23 00:36:06
8800 - 2025-12-23 00:36:22
8900 - 2025-12-23 00:36:38
9000 - 2025-12-23 00:36:54
9100 - 2025-12-23 00:37:09
9200 - 2025-12-23 00:37:25
9300 - 2025-12-23 00:37:41
9400 - 2025-12-23 00:37:57

In [ ]:
df_assin_2.head()

,sentence_pair_id,premise,hypothesis,relatedness_score,entailment_judgment,ministral_3b_reasoning
0,1.0,Uma criança risonha está segurando uma pistola...,Uma criança está segurando uma pistola de água,4.5,1.0,1
1,2.0,Os homens estão cuidadosamente colocando as ma...,Os homens estão colocando bagagens dentro do p...,4.5,1.0,1
2,3.0,Uma pessoa tem cabelo loiro e esvoaçante e est...,Um guitarrista tem cabelo loiro e esvoaçante,4.7,1.0,1
3,4.0,Batatas estão sendo fatiadas por um homem,O homem está fatiando a batata,4.7,1.0,1
4,5.0,Um caminhão está descendo rapidamente um morro,Um caminhão está rapidamente descendo o morro,4.9,1.0,1

# Carregando Ministral 3 - 3B - Base

In [ ]:
model_id = "mistralai/Ministral-3-3B-Base-2512"
model = Mistral3ForConditionalGeneration.from_pretrained(
    model_id,
    device_map="auto",
)
tokenizer = MistralCommonBackend.from_pretrained(model_id)

Unrecognized keys in `rope_parameters` for 'rope_type'='yarn': {'max_position_embeddings'}

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/458 [00:00<?, ?it/s]

In [ ]:
for i in range(len(df_assin_2)):
  premissa = df_assin_2.iloc[i]['premise']
  hipotese = df_assin_2.iloc[i]['hypothesis']

  prompt = zero_shot_prompt(premissa, hipotese)

  inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
  output = model.generate(**inputs, max_new_tokens=10)
  prompt_len = inputs["input_ids"].shape[1]
  generated_tokens = output[0][prompt_len:]
  resp = tokenizer.decode(generated_tokens, skip_special_tokens=True)

  df_assin_2.loc[i, 'ministral_3b_instruct'] = resp

  if i%100==0:
    print(f"{i} - {datetime.now(ZoneInfo("America/Sao_Paulo")).strftime("%Y-%m-%d %H:%M:%S")}")

df_assin_2.to_csv('/content/drive/MyDrive/Mestrado/TCC Pós/Dados/dados_mistral_3b_base.csv')

0 - 2025-12-23 00:38:20
100 - 2025-12-23 00:39:00
200 - 2025-12-23 00:39:40
300 - 2025-12-23 00:40:20
400 - 2025-12-23 00:41:00
500 - 2025-12-23 00:41:41
600 - 2025-12-23 00:42:21
700 - 2025-12-23 00:43:01
800 - 2025-12-23 00:43:41
900 - 2025-12-23 00:44:21
1000 - 2025-12-23 00:45:01
1100 - 2025-12-23 00:45:42
1200 - 2025-12-23 00:46:22
1300 - 2025-12-23 00:47:02
1400 - 2025-12-23 00:47:42
1500 - 2025-12-23 00:48:22
1600 - 2025-12-23 00:49:02
1700 - 2025-12-23 00:49:42
1800 - 2025-12-23 00:50:23
1900 - 2025-12-23 00:51:03
2000 - 2025-12-23 00:51:42
2100 - 2025-12-23 00:52:22
2200 - 2025-12-23 00:53:02
2300 - 2025-12-23 00:53:42
2400 - 2025-12-23 00:54:22
2500 - 2025-12-23 00:55:02
2600 - 2025-12-23 00:55:42
2700 - 2025-12-23 00:56:22
2800 - 2025-12-23 00:57:03
2900 - 2025-12-23 00:57:43
3000 - 2025-12-23 00:58:23
3100 - 2025-12-23 00:59:04
3200 - 2025-12-23 00:59:44
3300 - 2025-12-23 01:00:24
3400 - 2025-12-23 01:01:04
3500 - 2025-12-23 01:01:44
3600 - 2025-12-23 01:02:24
3700 - 2025-12-23 01:03:04
3800 - 2025-12-23 01:03:44
3900 - 2025-12-23 01:04:24
4000 - 2025-12-23 01:05:04
4100 - 2025-12-23 01:05:44
4200 - 2025-12-23 01:06:24
4300 - 2025-12-23 01:07:04
4400 - 2025-12-23 01:07:44
4500 - 2025-12-23 01:08:24
4600 - 2025-12-23 01:09:04
4700 - 2025-12-23 01:09:44
4800 - 2025-12-23 01:10:24
4900 - 2025-12-23 01:11:05
5000 - 2025-12-23 01:11:45
5100 - 2025-12-23 01:12:25
5200 - 2025-12-23 01:13:05
5300 - 2025-12-23 01:13:45
5400 - 2025-12-23 01:14:25
5500 - 2025-12-23 01:15:05
5600 - 2025-12-23 01:15:45
5700 - 2025-12-23 01:16:25
5800 - 2025-12-23 01:17:04
5900 - 2025-12-23 01:17:44
6000 - 2025-12-23 01:18:24
6100 - 2025-12-23 01:19:04
6200 - 2025-12-23 01:19:44
6300 - 2025-12-23 01:20:24
6400 - 2025-12-23 01:21:04
6500 - 2025-12-23 01:21:44
6600 - 2025-12-23 01:22:24
6700 - 2025-12-23 01:23:04
6800 - 2025-12-23 01:23:44
6900 - 2025-12-23 01:24:24
7000 - 2025-12-23 01:25:04
7100 - 2025-12-23 01:25:45
7200 - 2025-12-23 01:26:25
7300 - 2025-12-23 01:27:05
7400 - 2025-12-23 01:27:45
7500 - 2025-12-23 01:28:26
7600 - 2025-12-23 01:29:06
7700 - 2025-12-23 01:29:47
7800 - 2025-12-23 01:30:27
7900 - 2025-12-23 01:31:08
8000 - 2025-12-23 01:31:48
8100 - 2025-12-23 01:32:28
8200 - 2025-12-23 01:33:09
8300 - 2025-12-23 01:33:49
8400 - 2025-12-23 01:34:30
8500 - 2025-12-23 01:35:10
8600 - 2025-12-23 01:35:51
8700 - 2025-12-23 01:36:32
8800 - 2025-12-23 01:37:12
8900 - 2025-12-23 01:37:52
9000 - 2025-12-23 01:38:33
9100 - 2025-12-23 01:39:13
9200 - 2025-12-23 01:39:54
9300 - 2025-12-23 01:40:34
9400 - 2025-12-23 01:41:15
9500 - 2025-12-23 01:41:56
9600 - 2025-12-23 01:42:36
9700 - 2025-12-23 01:43:16
9800 - 2025-12-23 01:43:57
9900 - 2025-12-23 01:44:37
10000 - 2025-12-23 01:45:17
10100 - 2025-12-23 01:45:58
10200 - 2025-12-23 01:46:38
10300 - 2025-12-23 01:47:19
10400 - 2025-12-23 01:47:59
10500 - 2025-12-23 01:48:39
10600 - 2025-12-23 01:49:20
10700 - 2025-12-23 01:50:00
10800 - 2025-12-23 01:50:41
10900 - 2025-12-23 01:51:21
11000 - 2025-12-23 01:52:02
11100 - 2025-12-23 01:52:42
11200 - 2025-12-23 01:53:23
11300 - 2025-12-23 01:54:04
11400 - 2025-12-23 01:54:45
11500 - 2025-12-23 01:55:25
11600 - 2025-12-23 01:56:06
11700 - 2025-12-23 01:56:47
11800 - 2025-12-23 01:57:27
11900 - 2025-12-23 01:58:08
12000 - 2025-12-23 01:58:48
12100 - 2025-12-23 01:59:28
12200 - 2025-12-23 02:00:09
12300 - 2025-12-23 02:00:50

# Carregando Ministral 3 - 8B - Base

In [ ]:
model_id = "mistralai/Ministral-3-8B-Base-2512"
model = Mistral3ForConditionalGeneration.from_pretrained(
    model_id,
    device_map="auto",
)
tokenizer = MistralCommonBackend.from_pretrained(model_id)

config.json: 0.00B [00:00, ?B/s]

Unrecognized keys in `rope_parameters` for 'rope_type'='yarn': {'max_position_embeddings'}

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/531 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.language_model.embed_tokens.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/131 [00:00<?, ?B/s]

tekken.json:   0%|          | 0.00/16.8M [00:00<?, ?B/s]

In [ ]:
for i in range(len(df_assin_2)):
  premissa = df_assin_2.iloc[i]['premise']
  hipotese = df_assin_2.iloc[i]['hypothesis']

  prompt = zero_shot_prompt(premissa, hipotese)

  inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
  output = model.generate(**inputs, max_new_tokens=10)
  prompt_len = inputs["input_ids"].shape[1]
  generated_tokens = output[0][prompt_len:]
  resp = tokenizer.decode(generated_tokens, skip_special_tokens=True)

  df_assin_2.loc[i, 'ministral_8b_instruct'] = resp

  if i%100==0:
    print(f"{i} - {datetime.now(ZoneInfo("America/Sao_Paulo")).strftime("%Y-%m-%d %H:%M:%S")}")

df_assin_2.to_csv('/content/drive/MyDrive/Mestrado/TCC Pós/Dados/dados_mistral_8b_base.csv')

0 - 2025-12-23 02:02:50
100 - 2025-12-23 02:03:53
200 - 2025-12-23 02:04:55
300 - 2025-12-23 02:05:58
400 - 2025-12-23 02:07:00
500 - 2025-12-23 02:08:03
600 - 2025-12-23 02:09:05
700 - 2025-12-23 02:10:07
800 - 2025-12-23 02:11:10
900 - 2025-12-23 02:12:12
1000 - 2025-12-23 02:13:14
1100 - 2025-12-23 02:14:16
1200 - 2025-12-23 02:15:19
1300 - 2025-12-23 02:16:21
1400 - 2025-12-23 02:17:23
1500 - 2025-12-23 02:18:26
1600 - 2025-12-23 02:19:28
1700 - 2025-12-23 02:20:31
1800 - 2025-12-23 02:21:33
1900 - 2025-12-23 02:22:36
2000 - 2025-12-23 02:23:38
2100 - 2025-12-23 02:24:40
2200 - 2025-12-23 02:25:43
2300 - 2025-12-23 02:26:45
2400 - 2025-12-23 02:27:48
2500 - 2025-12-23 02:28:50
2600 - 2025-12-23 02:29:53
2700 - 2025-12-23 02:30:55
2800 - 2025-12-23 02:31:58
2900 - 2025-12-23 02:33:00
3000 - 2025-12-23 02:34:02
3100 - 2025-12-23 02:35:05
3200 - 2025-12-23 02:36:07
3300 - 2025-12-23 02:37:10
3400 - 2025-12-23 02:38:12
3500 - 2025-12-23 02:39:14
3600 - 2025-12-23 02:40:16
3700 - 2025-12-23 02:41:18
3800 - 2025-12-23 02:42:20
3900 - 2025-12-23 02:43:22
4000 - 2025-12-23 02:44:24
4100 - 2025-12-23 02:45:26
4200 - 2025-12-23 02:46:28
4300 - 2025-12-23 02:47:30
4400 - 2025-12-23 02:48:32
4500 - 2025-12-23 02:49:35
4600 - 2025-12-23 02:50:36
4700 - 2025-12-23 02:51:38
4800 - 2025-12-23 02:52:40
4900 - 2025-12-23 02:53:42
5000 - 2025-12-23 02:54:44
5100 - 2025-12-23 02:55:46
5200 - 2025-12-23 02:56:48
5300 - 2025-12-23 02:57:49
5400 - 2025-12-23 02:58:51
5500 - 2025-12-23 02:59:53
5600 - 2025-12-23 03:00:55
5700 - 2025-12-23 03:01:57
5800 - 2025-12-23 03:02:59
5900 - 2025-12-23 03:04:01
6000 - 2025-12-23 03:05:03
6100 - 2025-12-23 03:06:05
6200 - 2025-12-23 03:07:07
6300 - 2025-12-23 03:08:09
6400 - 2025-12-23 03:09:11
6500 - 2025-12-23 03:10:13
6600 - 2025-12-23 03:11:15
6700 - 2025-12-23 03:12:18
6800 - 2025-12-23 03:13:20
6900 - 2025-12-23 03:14:23
7000 - 2025-12-23 03:15:25
7100 - 2025-12-23 03:16:28
7200 - 2025-12-23 03:17:30
7300 - 2025-12-23 03:18:33
7400 - 2025-12-23 03:19:35
7500 - 2025-12-23 03:20:38
7600 - 2025-12-23 03:21:40
7700 - 2025-12-23 03:22:43
7800 - 2025-12-23 03:23:45
7900 - 2025-12-23 03:24:47
8000 - 2025-12-23 03:25:50
8100 - 2025-12-23 03:26:52
8200 - 2025-12-23 03:27:54
8300 - 2025-12-23 03:28:56
8400 - 2025-12-23 03:29:58
8500 - 2025-12-23 03:31:00
8600 - 2025-12-23 03:32:03
8700 - 2025-12-23 03:33:05
8800 - 2025-12-23 03:34:08
8900 - 2025-12-23 03:35:10
9000 - 2025-12-23 03:36:13
9100 - 2025-12-23 03:37:15
9200 - 2025-12-23 03:38:17
9300 - 2025-12-23 03:39:19
9400 - 2025-12-23 03:40:21
9500 - 2025-12-23 03:41:23
9600 - 2025-12-23 03:42:25
9700 - 2025-12-23 03:43:26
9800 - 2025-12-23 03:44:27
9900 - 2025-12-23 03:45:29
10000 - 2025-12-23 03:46:30
10100 - 2025-12-23 03:47:31
10200 - 2025-12-23 03:48:32
10300 - 2025-12-23 03:49:33
10400 - 2025-12-23 03:50:35
10500 - 2025-12-23 03:51:36
10600 - 2025-12-23 03:52:38
10700 - 2025-12-23 03:53:39
10800 - 2025-12-23 03:54:41
10900 - 2025-12-23 03:55:42
11000 - 2025-12-23 03:56:44
11100 - 2025-12-23 03:57:45
11200 - 2025-12-23 03:58:46
11300 - 2025-12-23 03:59:48
11400 - 2025-12-23 04:00:49
11500 - 2025-12-23 04:01:51
11600 - 2025-12-23 04:02:52
11700 - 2025-12-23 04:03:54
11800 - 2025-12-23 04:04:55
11900 - 2025-12-23 04:05:56
12000 - 2025-12-23 04:06:57
12100 - 2025-12-23 04:07:58
12200 - 2025-12-23 04:08:59
12300 - 2025-12-23 04:10:01
12400 - 2025-12-23 04:11:02
12500 - 2025-12-23 04:12:04
12600 - 2025-12-23 04:13:05
12700 - 2025-12-23 04:14:07
12800 - 2025-12-23 04:15:08
12900 - 2025-12-23 04:16:09
13000 - 2025-12-23 04:17:11
13100 - 2025-12-23 04:18:13
13200 - 2025-12-23 04:19:14
13300 - 2025-12-23 04:20:16
13400 - 2025-12-23 04:21:18
13500 - 2025-12-23 04:22:19
13600 - 2025-12-23 04:23:21
13700 - 2025-12-23 04:24:22
13800 - 2025-12-23 04:25:24
13900 - 2025-12-23 04:26:26
14000 - 2025-12-23 04:27:28
14100 - 2025-12-23 04:28:30
14200 - 2025-12-23 04:29:32
14300 - 2025-12-23 04:30:34
14400 - 2025-12-23 04:31:35
14500 - 2025-12-23 04:32:37
14600 - 2025-12-23 04:33:38
14700 - 2025-12-23 04:34:39
14800 - 2025-12-23 04:35:41
14900 - 2025-12-23 04:36:43
15000 - 2025-12-23 04:37:44
15100 - 2025-12-23 04:38:46
15200 - 2025-12-23 04:39:48
15300 - 2025-12-23 04:40:49

# Carregando Ministral 3 - 8B - Reasoning

In [ ]:
model_id = "mistralai/Ministral-3-8B-Reasoning-2512"
model = Mistral3ForConditionalGeneration.from_pretrained(
    model_id,
    device_map="auto",
)
tokenizer = MistralCommonBackend.from_pretrained(model_id)

config.json: 0.00B [00:00, ?B/s]

Unrecognized keys in `rope_parameters` for 'rope_type'='yarn': {'max_position_embeddings'}

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/531 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.language_model.embed_tokens.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/131 [00:00<?, ?B/s]

tekken.json:   0%|          | 0.00/16.8M [00:00<?, ?B/s]

In [ ]:
for i in range(len(df_assin_2)):
  premissa = df_assin_2.iloc[i]['premise']
  hipotese = df_assin_2.iloc[i]['hypothesis']

  prompt = zero_shot_prompt(premissa, hipotese)

  inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
  output = model.generate(**inputs, max_new_tokens=10)
  prompt_len = inputs["input_ids"].shape[1]
  generated_tokens = output[0][prompt_len:]
  resp = tokenizer.decode(generated_tokens, skip_special_tokens=True)

  df_assin_2.loc[i, 'ministral_8b_reasoning'] = resp

  if i%100==0:
    print(f"{i} - {datetime.now(ZoneInfo("America/Sao_Paulo")).strftime("%Y-%m-%d %H:%M:%S")}")

df_assin_2.to_csv('/content/drive/MyDrive/Mestrado/TCC Pós/Dados/dados_mistral_8b_reasoning.csv')

0 - 2025-12-23 04:42:25
100 - 2025-12-23 04:42:55
200 - 2025-12-23 04:43:26
300 - 2025-12-23 04:43:56
400 - 2025-12-23 04:44:27
500 - 2025-12-23 04:44:57
600 - 2025-12-23 04:45:28
700 - 2025-12-23 04:45:58
800 - 2025-12-23 04:46:28
900 - 2025-12-23 04:46:58
1000 - 2025-12-23 04:47:28
1100 - 2025-12-23 04:47:58
1200 - 2025-12-23 04:48:29
1300 - 2025-12-23 04:48:59
1400 - 2025-12-23 04:49:29
1500 - 2025-12-23 04:50:00
1600 - 2025-12-23 04:50:30
1700 - 2025-12-23 04:51:00
1800 - 2025-12-23 04:51:31
1900 - 2025-12-23 04:52:01
2000 - 2025-12-23 04:52:32
2100 - 2025-12-23 04:53:02
2200 - 2025-12-23 04:53:32
2300 - 2025-12-23 04:54:03
2400 - 2025-12-23 04:54:33
2500 - 2025-12-23 04:55:04
2600 - 2025-12-23 04:55:34
2700 - 2025-12-23 04:56:04
2800 - 2025-12-23 04:56:35
2900 - 2025-12-23 04:57:06
3000 - 2025-12-23 04:57:36
3100 - 2025-12-23 04:58:07
3200 - 2025-12-23 04:58:37
3300 - 2025-12-23 04:59:08
3400 - 2025-12-23 04:59:38
3500 - 2025-12-23 05:00:08
3600 - 2025-12-23 05:00:37
3700 - 2025-12-23 05:01:07
3800 - 2025-12-23 05:01:38
3900 - 2025-12-23 05:02:08
4000 - 2025-12-23 05:02:37
4100 - 2025-12-23 05:03:08
4200 - 2025-12-23 05:03:37
4300 - 2025-12-23 05:04:07
4400 - 2025-12-23 05:04:37
4500 - 2025-12-23 05:05:07
4600 - 2025-12-23 05:05:37
4700 - 2025-12-23 05:06:07
4800 - 2025-12-23 05:06:37
4900 - 2025-12-23 05:07:07
5000 - 2025-12-23 05:07:38
5100 - 2025-12-23 05:08:08
5200 - 2025-12-23 05:08:38
5300 - 2025-12-23 05:09:08
5400 - 2025-12-23 05:09:37
5500 - 2025-12-23 05:10:07
5600 - 2025-12-23 05:10:38
5700 - 2025-12-23 05:11:08
5800 - 2025-12-23 05:11:38
5900 - 2025-12-23 05:12:08
6000 - 2025-12-23 05:12:38
6100 - 2025-12-23 05:13:07
6200 - 2025-12-23 05:13:37
6300 - 2025-12-23 05:14:07
6400 - 2025-12-23 05:14:37
6500 - 2025-12-23 05:15:07
6600 - 2025-12-23 05:15:37
6700 - 2025-12-23 05:16:08
6800 - 2025-12-23 05:16:38
6900 - 2025-12-23 05:17:09
7000 - 2025-12-23 05:17:39
7100 - 2025-12-23 05:18:10
7200 - 2025-12-23 05:18:40
7300 - 2025-12-23 05:19:10
7400 - 2025-12-23 05:19:41
7500 - 2025-12-23 05:20:11
7600 - 2025-12-23 05:20:42
7700 - 2025-12-23 05:21:12
7800 - 2025-12-23 05:21:43
7900 - 2025-12-23 05:22:13
8000 - 2025-12-23 05:22:43
8100 - 2025-12-23 05:23:14
8200 - 2025-12-23 05:23:44
8300 - 2025-12-23 05:24:14
8400 - 2025-12-23 05:24:44
8500 - 2025-12-23 05:25:15
8600 - 2025-12-23 05:25:45
8700 - 2025-12-23 05:26:16
8800 - 2025-12-23 05:26:46
8900 - 2025-12-23 05:27:17
9000 - 2025-12-23 05:27:47
9100 - 2025-12-23 05:28:17
9200 - 2025-12-23 05:28:47
9300 - 2025-12-23 05:29:17
9400 - 2025-12-23 05:29:48
9500 - 2025-12-23 05:30:18
9600 - 2025-12-23 05:30:47
9700 - 2025-12-23 05:31:16
9800 - 2025-12-23 05:31:45
9900 - 2025-12-23 05:32:14
10000 - 2025-12-23 05:32:43
10100 - 2025-12-23 05:33:12
10200 - 2025-12-23 05:33:41
10300 - 2025-12-23 05:34:10
10400 - 2025-12-23 05:34:39
10500 - 2025-12-23 05:35:08
10600 - 2025-12-23 05:35:37
10700 - 2025-12-23 05:36:06
10800 - 2025-12-23 05:36:35
10900 - 2025-12-23 05:37:04
11000 - 2025-12-23 05:37:33
11100 - 2025-12-23 05:38:02
11200 - 2025-12-23 05:38:31
11300 - 2025-12-23 05:39:00
11400 - 2025-12-23 05:39:29
11500 - 2025-12-23 05:39:58
11600 - 2025-12-23 05:40:27
11700 - 2025-12-23 05:40:56
11800 - 2025-12-23 05:41:25
11900 - 2025-12-23 05:41:54
12000 - 2025-12-23 05:42:23
12100 - 2025-12-23 05:42:52
12200 - 2025-12-23 05:43:21
12300 - 2025-12-23 05:43:50
12400 - 2025-12-23 05:44:20
12500 - 2025-12-23 05:44:49
12600 - 2025-12-23 05:45:18
12700 - 2025-12-23 05:45:47
12800 - 2025-12-23 05:46:16
12900 - 2025-12-23 05:46:45
13000 - 2025-12-23 05:47:14
13100 - 2025-12-23 05:47:43
13200 - 2025-12-23 05:48:12
13300 - 2025-12-23 05:48:41
13400 - 2025-12-23 05:49:09
13500 - 2025-12-23 05:49:38
13600 - 2025-12-23 05:50:07
13700 - 2025-12-23 05:50:36
13800 - 2025-12-23 05:51:05
13900 - 2025-12-23 05:51:34
14000 - 2025-12-23 05:52:03
14100 - 2025-12-23 05:52:32
14200 - 2025-12-23 05:53:01
14300 - 2025-12-23 05:53:30
14400 - 2025-12-23 05:53:59
14500 - 2025-12-23 05:54:28
14600 - 2025-12-23 05:54:57
14700 - 2025-12-23 05:55:26
14800 - 2025-12-23 05:55:55
14900 - 2025-12-23 05:56:24
15000 - 2025-12-23 05:56:53
15100 - 2025-12-23 05:57:22
15200 - 2025-12-23 05:57:51
15300 - 2025-12-23 05:58:20
15400 - 2025-12-23 05:58:50
15500 - 2025-12-23 05:59:19
15600 - 2025-12-23 05:59:49
15700 - 2025-12-23 06:00:18
15800 - 2025-12-23 06:00:48
15900 - 2025-12-23 06:01:17
16000 - 2025-12-23 06:01:47
16100 - 2025-12-23 06:02:17
16200 - 2025-12-23 06:02:46
16300 - 2025-12-23 06:03:16
16400 - 2025-12-23 06:03:45
16500 - 2025-12-23 06:04:15
16600 - 2025-12-23 06:04:44
16700 - 2025-12-23 06:05:14
16800 - 2025-12-23 06:05:43
16900 - 2025-12-23 06:06:13
17000 - 2025-12-23 06:06:42
17100 - 2025-12-23 06:07:12
17200 - 2025-12-23 06:07:41
17300 - 2025-12-23 06:08:11
17400 - 2025-12-23 06:08:40
17500 - 2025-12-23 06:09:10
17600 - 2025-12-23 06:09:39
17700 - 2025-12-23 06:10:09
17800 - 2025-12-23 06:10:38
17900 - 2025-12-23 06:11:08
18000 - 2025-12-23 06:11:37
18100 - 2025-12-23 06:12:07
18200 - 2025-12-23 06:12:36